config:
  adminAddr: 0.0.0.0:23500
  statsAddr: 0.0.0.0:23501
  readinessAddr: 0.0.0.0:23502
llm:
  port: 4001
  models:
    - name: "openai/gpt-3.5-turbo"
      provider: openAI
      params:
        baseUrl: http://mock-server:8081/v1
        model: gpt-3.5-turbo
