config:
  adminAddr: 0.0.0.0:23500
  statsAddr: 0.0.0.0:23501
  readinessAddr: 0.0.0.0:23502
binds:
  - port: 4001
    listeners:
      - name: default
        protocol: HTTP
        routes:
          - matches:
              - path:
                  pathPrefix: /
            backends:
              - ai:
                  name: openai
                  hostOverride: mock-server:8081
                  provider:
                    openAI:
                      model: gpt-3.5-turbo
